apiVersion: v1
kind: Pod
metadata:
  name: goserver
  labels:
    name: goserver
spec:
  containers:
  - name: goserver
    image: "leonardomdeoli/hello-go-serve:latest" 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"